language: node_js
node_js:
- lts/boron
- node
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: YE5/iiJmMcwfQ3IUVgV8Ujm+fok7BAhi50rk8A+6pmbUknELC8DNNBTxqKC73sDr/bUmUTvYMgr5eTqanrggN8FsmHc92wf2D5mTqlRFU/wT6r3zxdmNBpDLxCP3fyPCbYNScMpgoT9WBOIQhVFvgb6+9VVcXUAHZnbVXO5VeXqmteUs/U5XZoJl5TdBUEy02G++kxWz0XT+Bt37e7OavGG8AWcxkaOooLp4+aiV6I/3z94zNNR09EW8N4IEnBN6ZhoWYgRygaqNLTQ9ZoCQeqgheLwtwJXdAQInAFy7fwCmRuOvw1h2ssCoSC6KHtNPqeGc7ZoLXYhABzC3PAgaxWCxhD9NY+ywiifY5PxjxfrvsiilQxYOdni4ZVtPi5zkZQsPyFpkVeYvzz8U1Xlf346XV+JhuwWXMpix/6Y8dmmOsXt7xQyYX5gltgp0y9ZCtyqwJV8irox/mQxTbyFXMRvCQLTvy0XPRCXafGXAblcBTbfOqmxq/KwdyuSGCkvNZH0/KOjzzaxdGB7KlUVoRgWIl+XQM2SDI2LHv/mPJufG3udHVBYu3g+KKBHlWbPAoDoRwS0cLk++EsYG3urfKqVyqXukYL9pDzvEkMnIu6etCltTL9430vplWDsWmE8vlvDIORoPn/7EOIsVB5q74HjfalmcdXiudYkAZ0zwPFE=
  file:
    - "mdast-util-to-string.js"
    - "mdast-util-to-string.min.js"
  on:
    tags: true
